name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mock-api:
        image: firstclasspostcodes/mock:latest
        env:
          PORT: 3000
        ports:
          - '3000:3000'

    steps:
      - uses: actions/checkout@v1

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Lint, Analyse & Test
        run: |
          composer run-script lint
          composer run-script analyse
          composer run-script test
        env:
          API_HOST: localhost:3000
          API_KEY: '111111111111'